#
# Knight Launcher language file
# Language: pt-BR - Português (Brasil)
#
# Contributors:
# - gugaarleo @ Discord, 242096877191954432 @ Discord
# - stret @ Discord, 229051060486930443 @ Discord
#

# Generic buttons
b.launch="Iniciar"
b.mods="Mods"
b.settings="Configurações"
b.editors="Editores"
b.auction="Leilões"
b.open_mods_dir="Abrir pasta de mods"
b.get_mods="Obter mods pelo Discord"
b.refresh="Recarregar"
b.update="Atualizar"
b.enable="Ativar"
b.disable="Desativar"
b.bugs="Reportar um bug"
b.close="Fechar"
b.minimize="Minimizar"
b.donate="Doar"
b.discord="Discord"
b.learn_more="Saiba mais"
b.play="Jogar Agora"
b.install="Instalar"
b.mod_store="Loja de Mods"
b.recommended_settings="Carregar configurações recomendadas"
b.reset_default="Redefinir valores para o padrão"
b.activate="Ativar"
b.beta_code_revalidate="Revalidar meus códigos de Beta"
b.beta_code_clear_local="Limpar códigos de Beta armazenados localmente"
b.copy_logs="Copiar Logs para a área de transferência"
b.open_game_dir="Abrir pasta do jogo"
b.enable_all_mods="Ativar todos os mods"
b.disable_all_mods="Desativar todos os mods"
b.add="Adicionar"
b.remove="Remover"
b.back="Voltar"
b.server_notice="Problemas"
b.jvm_arg_docs="Documentação de argumentos do JVM"

# Messages
m.platform="Platforma"
m.rebuilds="Limpeza de arquivos"
m.keep_open="Manter aberto ao iniciar"
m.create_shortcut="Criar atalho"
m.allocated_memory="Mémoria alocada (RAM)"
m.disable_explicit_gc="Desabilitar GC Explícito"
m.mods_installed="Mods instalados"
m.language="Linguagem"
m.apply="Aplicando configurações do jogo..."
m.rebuild="Reconstruindo..."
m.mount="Montando mods..."
m.game_launching="Iniciando jogo, por favor aguarde"
m.save="Salvar"
m.prompt_restart_required="As alterações entrarão em vigor após reiniciar."
m.jvm_patcher_accept="Sim, comece o patching"
m.jvm_patcher_decline="Não, obrigado"
m.jvm_patcher_header="Preparando tudo, isso levará alguns minutos..."
m.jvm_patcher_subheader="Estamos certificando que o seu jogo está rodando em 64-bit, por favor não feche essa janela."
m.jvm_patcher_download="Baixando MV do Java (isso pode durar um tempo)..."
m.jvm_patcher_delete="Deletando antiga MV do Java..."
m.jvm_patcher_extract="Extraindo nova MV do Java..."
m.jvm_patcher_finish="Patching terminado, inicializando no Knight Launcher..."
m.coming_soon="Em breve..."
m.extratxt_write_arguments="Argumentos do JVM adicionais para utilizar na inicialização do jogo"
m.file_cleaning_explained="Limpar arquivos do jogo quando um mod é adicionado, modificado ou removido."
m.keep_open_explained="Previne que o launcher feche quando o jogo é iniciado."
m.create_shortcut_explained="Adiciona um atalho para iniciar o launcher caso não tenha nenhum."
m.autoupdate="Atualizar automaticamente"
m.autoupdate_explained="Automaticamente faz o download e instala atualizações do launcher quando disponível"
m.explicit_gc_explained="Conserta alguns eventos de coleta de lixo \"stop-the-world\"."
m.rebuild_files="Redefinir Arquivos do Jogo"
m.rebuild_files_explained="Redefine sua instalação para um estado completamente original"
m.file_purging="Purgar Arquivos"
m.file_purging_explained="Purga arquivos do jogo antes de limpar arquivos para remover sobras de arquivos não originais"
m.use_custom_gc="Utilizar comportamento diferente de GC"
m.use_custom_gc_explained="Muda como que a MV do Java do jogo vai realizar a coleta de lixo."
m.use_ingame_rpc="Integração do Discord"
m.use_ingame_rpc_explained="Mostra o que você está fazendo pelo mundo de Cradle no seu status do Discord"
m.jvm_patcher_confirm_header="Knight Launcher pode automaticamente fazer um patch em seu jogo para que use uma MV do Java 64-bits"
m.jvm_patcher_confirm_subheader="Você gostaria deste patch? Você pode sempre reiniciar este patcher no menu de configurações"
m.force_jvm_patch="Faz o patch de uma MV Java de 64-bits"
m.force_jvm_patch_explained="Automaticamente baixa e instala uma MV Java de 64-bit para sua instalação de Spiral Knights."
m.mod_disclaimer="Modificações do cliente não sao aprovadas ou diretamente relacionadas com ou pelo Knight Launcher nem pela Grey Havens. Use diante de seu próprio risco e responsabilidade. Sempre certifique-se de apenas instalar mods baixados pelo servidor do Discord do Knight Launcher, e nunca por terceiros."
m.server="Servidor: {0}"
m.banner_title_default="Ah, não"
m.banner_subtitle_default="Esse servidor não está atualmente anunciando nada"
m.server_info="Ver informação do servidor"
m.server_info_text="Nome: {0}\nDescrição: {1}\nVersão: {2}\nGerenciado por: {3}\n"
m.server_info_text_siteurl="Website: {0}\n"
m.server_info_text_communityurl="Comunidade: {0}\n"
m.server_info_text_sourcecode="Código fonte: {0}\n"
m.server_info_text_disclaimer="\n* Nem a sua atividade em serviços de terceiros e nem a deles é aprovada\npelo Knight Launcher. Jogue por sua conta e risco."
m.players_online="Jogadores Online"
m.players_online_text="Essa contagems de jogadores é uma aproximação baseada no número atual de jogadores online pela Steam.\nA aproximação é realizada por somar o número de jogadores online pela Steam por 1,4x para contar por usuários Independentes\n\nSe esse número for 0 é provável de que a Steam esteja temporáriamente Offline para manutenção, e será restaurada em breve."
m.alt_mode_title="Lançar em Modo de Alt"
m.alt_mode_text="Mantenha a tecla ALT (OPTION para macOS) ou SHIFT pressionada para iniciar no Modo Alt e economizar\nrecursos computacionais para sua instância principal de Spiral Knights"
m.changelog="Registro de Alterações do Knight Launcher"
m.warning_notice="Aviso"
m.warning="Aviso"
m.game_java_vm_data="VM Java do jogo: {0}"
m.launch_thirdparty_data="Recuperando dados do: {0}..."
m.launch_thirdparty_download="Fazendo o download {0}... (isso pode durar um tempo)"
m.launch_thirdparty_update="Atualizando {0}... (isso pode durar um tempo)"
m.launch_thirdparty_bundle_regen="Regenerando pacote padrão para {0}..."
m.launch_thirdparty_start="Iniciando {0}, por favor aguarde"
m.editor_loading="Carregando editor..."
m.editor_model="Visualizador de Modelos"
m.editor_scene="Editor de Cenas"
m.editor_scene_legacy="Editor de Cenas (LEGADO)"
m.editor_interface="Editor de Interface"
m.editor_particle="Editor de Partículas"
m.editor_crucible="Editor do Crucible"
m.powered_by_spiralview="Com tecnologia do SpiralView {0} "
m.editor_fake_loading_1="Compilando configs..."
m.editor_fake_loading_2="Criando interface..."
m.editor_fake_loading_3="Quase lá..."
m.refresh="Recarregando..."
m.modlist_searchbox_placeholder="Digite o nome do mod ou autor..."
m.search="Buscar"
m.enabled="Ativado"
m.mod_footer="Versão: {0}. Autor: {1}."
m.resource_mod="Mod de Recursos"
m.code_mod="Mod de Código"
m.class_mod="Mod de Classe"
m.modlist_footer="Mostrando {0} de {1} mod(s)."
m.days="Dia(s)"
m.hours="Hora(s)"
m.minutes="Minuto(s)"
m.seconds="Segundo(s)"
m.less_than_minute="menos de um minuto"
m.online="Online"
m.offline="Offline"
m.recently_restarted="Recentemente reiniciado"
m.flamingo_status="Serviços Backend: {0}"
m.flamingo_version="Versão do Flamingo: {0}"
m.flamingo_uptime="Uptime do Flamingo: {0}"
m.beta_code_activate="Ativar um Código de Beta"
m.beta_code_invalid="Por favor insira um código de Beta Válido."
m.beta_code_error="Um erro inesperado ocorreu."
m.beta_code_success="Código de Beta ativado com sucesso. (Verifique a lista de servidores)"
m.beta_code_duplicate="Você já ativou esse código de Beta."
m.beta_code_already_used="Esse código de Beta já foi ativado."
m.beta_code_already_used_same="Você já ativou esse código de Beta."
m.beta_code_not_exists="Esse código de Beta não existe."
m.beta_code_activated="Códigos de Beta ativados"
m.beta_code_revalidated="Códigos de Beta revalidados."
m.beta_code_cleared="Códigos de Beta limpos."
m.destructive_action="AVISO: Essa ação é destrutiva.\nApenas continue se você sabe o que está fazendo.\n\nAperte \"Sim\" para confirmar."
m.connection_settings="Configurações de Conexão"
m.connection_settings_thirdparty_disclaimer="Apenas se aplica para conexões de servidor oficiais."
m.server_address="Endereço do servidor."
m.port="Porta"
m.public_key="Chave pública"
m.getdown_url="URL de Getdown"
m.credits="Creditos"
m.kl_version="versão do Knight Launcher: {0}"
m.logs_copied="Registros copiados para a área de transferência"
m.beta_code_entitling="entitulando você para {0}"
m.modpack="Modpack"
m.viewing_settings="Vendo configurações para {0}."
m.viewing_mods="Vendo mods para {0}."
m.viewing_editors="Vendo editores para {0}."
# For localization contributions: Only translate credits_template, not the rest.
m.credits_template="Contribuidores do GitHub:\n{0}\n\nLocalização:\n{1}\n\nTestes/Controle de Qualidade:\n{2}\n\nBibliotecas de terceiros:\n{3}"
m.credits_contributors="- Lucas (maintainer), Crowfunder, CafuneAndChill, yihleego, quardbreak."
m.credits_translators="- Arabic: asan_ploto.\n- Chinese: yihleego.\n- Deutsch: Biral, Airbee.\n- Eesti: Thyrux.\n- English: Lucas.\n- Español: Lucas.\n- Français: PtitKrugger.\n- Italiano: Lawn, Kaus, Top-Platinum.\n- Japanese: octopews.\n- Polski: Crowfunder.\n- Português (Brasil): Stret, Gugaarleo.\n- Russian: milliath, Puzovoz, quardbreak."
m.credits_qa="- Nurr, yihleego, Bidoknight, Carpvindra, Mushspore, CafuneAndChill, Xan, analarmingalarm, parma, loonadra, ultrongr, milliath, Puzovoz, Stret, 3xample, top_platinum, Criptobeta."
m.credits_libs="- Guava, Guice, Apache Commons IO, Apache Commons Text, Image4J, Zip4J, flatlaf, discord-rpc, mslinks, org.json, jIconFont, samskivert, JHLabs Filters, OSHI."
m.animated_banners_disable="Desabilitar banners animados"
m.animated_banners_enable="Habilitar banners animados"
m.add_server="Adicionar um servidor"
m.add_server_text="Servidores de terceiros serão adicionados automaticamente para essa lista quando estiverem publicamente disponíveis\n\nVocê pode reinvindicar acesso de Beta para servidores de terceiros pela aba de Betas nas configurações do Launcher."
m.banner_starts_at_time_remaining="Começa em {0}"
m.banner_starts_at_time="Começa {0}"
m.banner_ends_at_time_remaining="Termina em {0}"
m.banner_ends_at_time="Termina {0}"
m.banner_ends_at_ended="Esse evento terminou"
m.alt_mode="Modo de Alt"
m.purge="Purgando arquivos antigos..."
m.reset_code="Redefinindo código e configurações para o original..."
m.loading="Carregando..."
m.settings_warning="Modificar essa configuração vai alterar funcionalidades importantes do launcher\nA maioria dos usuários nunca vão precisar interagir com isso, tenha certeza que você sabe o que está fazendo.\n\nVocê deseja proceder?"
m.mod_warnings="{0} tem os seguintes avisos:\n\n{1}"
m.warning_file_headers="Alguns arquivos desse mod não vão ser montados:\n{0}\n\n{1}"
m.warning_file_headers_protected="Isso é porque a modificação deles é protegida por ser propensa à mexer com atualizações do jogo."
m.warning_file_headers_illegal="Isso é porque a modificação deles é normalmente feita para motivos de trapaça."
m.warning_file_headers_outdated="Isso é porque a sua contraparte original é mais recente."
m.warning_incompatible_px="Esse mod não é compatível com a versão atual do jogo. Necessita de uma atualização."
m.warning_incompatible_jdk="Esse mod não é compatível com a MV Java atual. Por favor faça um patch de uma nova MV Java."
m.refresh_tooltip="Recarregue a lista de mods e monte novamente."
m.launching="Iniciando"
m.add_mod_tooltip="Adicionar um mod"
m.remove_mod="Remover {0}"
m.game_settings="Configurações do jogo"
m.repair_game_files="Reparar arquivos do jogo"
m.launch_popup_tooltip="Configurações de inicialização..."
m.scene_editor_legacy_warning="Não utilize esse Editor de Cenas Legado para produzir conteúdo que você pretende submeter para o programa do Crucible do Coliseu. \nEm vez disso utilize o Editor do Crucible que pode ser acessado dentro do jogo. \n\nEsse editor Legado pode quebrar a qualquer momento e suporte futuro para ele não é garantido.\n\nVocê gostaria de proceder?"
m.crucible_editor_warning="O Editor do Crucible é mantido exclusivamente pela Grey Havens, e esse launcher não tem aprovação ou associação.\nIsso é simplesmente um atalho para acessar o mesmo editor que você acessaria no jogo.\n\nUtilizar o Editor do Crucible por fora do jogo não é oficialmente apoiado...\nCoisas podem ou não funcionar corretamente, use por sua conta em risco.\n\nQuaisquer criações que você fizer tem que obedecer com os Termos de Servido do Coliseum Crucible:\nhttps://wiki.spiralknights.com/Coliseum_Crucible_Terms_and_Conditions \n\nGaranta que quaisquer bugs que você pretende submeter podem ser reproduzidos no editor dentro do jogo.\n\nVocê gostaria de proceder?"
m.scheduled_maintenance_warning="Os servidores do jogo estão atualmente sob uma janela de manutenção.\nSua sessão do jogo pode sofrer interrupções, ou você pode não conseguir fazer o log in em geral.\n\nA manutenção acaba às: {0}. (isso é mostrado em seu horário local)\n\nO horário acima é uma estimativa oficial, mas sempre pode variar.\nPor favor verifique os fóruns do jogo para mais informações."
m.invalid_additional_args_warning="Um ou mais argumentos do JVM na sua configuração de Argumentos Adicionais (Extra.txt) foram vistos como inválidos.\n\nPor favor vá para Configurações → Avançado e verifique-as. Leia os registros do Knight Launcher para mais informações.\n\nTodas elas vão ser ignoradas para essa inicialização."
m.invalid_additional_args_save_warning="Um ou mais argumentos do JVM na sua configuração de Argumentos Adicionais (Extra.txt) foram vistos como inválidos, e eles foram forçadamente redefinidos para o padrão.\n\nPor favor vá para Configurações → Avançado e verifique-as. Leia os registros do Knight Launcher para mais informações."

# Options (usually on comboboxes)
o.steam="Steam"
o.standalone="Independente"
o.memory_256="256 MB"
o.memory_512="512 MB"
o.memory_768="768 MB"
o.memory_1024="1 GB"
o.memory_1280="1.25 GB"
o.memory_1536="1.5 GB"
o.memory_1792="1.75 GB"
o.memory_2048="2 GB"
o.memory_2304="2.25 GB"
o.memory_2560="2.5 GB"
o.memory_2816="2.75 GB"
o.memory_3072="3 GB"
o.memory_3328="3.25 GB"
o.memory_3584="3.5 GB"
o.memory_3840="3.75 GB"
o.memory_4096="4 GB"

# Window titles
t.main="Knight Launcher ({0})"
t.error="Knight Launcher Erro"
t.warning="Aviso do Knight Launcher"
t.jvm_patcher="Knight Launcher Patcher MV Java"
t.game_launch_error="Erro ao iniciar jogo"
t.server_info="Informação do Servidor"
t.scheduled_maintenance="Manutenção Programada"
t.invalid_additional_args="Argumentos Adicionais Inválidos (Extra.txt)"

# Tab names for tabbed panes, mainly used for the Settings menu
tab.launcher="Launcher"
tab.game="Jogo"
tab.betas="Betas"
tab.advanced="Avançado"
tab.about="Sobre"

# Error messages
error.invalid_dir="Você precisa colocar esse .jar dentro do seu diretório principal do Spiral Knights {0}"
error.game_launch="Não foi possível iniciar o jogo.\n\nÉ recomendado que você tente qualquer uma das soluções a seguir em qualquer ordem:\n- Na aba \"Jogo\" nas configurações do launcher pressione o botão de \"Carregar configurações recomendadas\".\n- Reduza a memória alocada na aba \"Jogo\" nas configurações do launcher.\n- Na aba \"Jogo\" nas configurações do launcher pressione o botão de \"Redefinir valores para o padrão\".\n- Faça outro patch da VM Java  na aba \"Jogo\" nas configurações do launcher.\n\nSe isso ainda não resolver o problema você pode buscar por suporte técnico no Discord.\n\nQuando for submeter um pedido de ajuda pelo Discord lembre-se de anexar TODOS os seus arquivos de logs com o pedido.\nVocê pode conseguir TODOS os seus registros automaticamente entrando nas Configurações do Launcher → Sobre → Copiar Logs para a área de transferência, e depois pressionar CTRL + V no Discord."
error.start_location="O arquivo .jar parece ter sido colocado no diretório errado.\nEm alguns casos isso acontece devido a um falso positivo e pode ser ignorado. O Knight Launcher tentará iniciar normalmente.\nSe isso persistir tente utilizar o arquivo Batch (KnightLauncher_windows.bat) para Windows\nou o arquivo Shell (KnightLauncher_mac_linux.sh) para OSX/Linux."
error.start_location_steam_path="\nAdicionalmente, nós detectamos o seguinte caminho para o Steam: \n{0}"
error.flamingo_offline="Não foi possível conectar ao Flamingo.\nAlgumas funcionalidades do launcher podem não estar totalmente disponíveis."
error.no_compatible_jvm="Nenhuma VM Java compatível para iniciar o editor com."
error.folders_within_mods_folder="Existem pastas dentro da pasta de mods.\nVocê não precisa extrair o arquivo .zip, apenas arraste o arquivo .zip para a pasta de mods."
error.unsupported_64bit="O seu sistema não tem suporte ao patching de 64-bits da MV Java."
error.not_supported="Não suportado."
error.mod_file_format="Apenas extensões de arquivo .zip, .jar e .modpack são suportadas, por favor tente novamente."
error.incompatible_mod="Pelo menos um mod incompatível foi encontrado. Todos eles serão automaticamente definidos como desativados.\nAtualize eles para poder restaurar sua funcionalidade."

# Discord RPC strings
presence.using="Utilizando o Knight Launcher"
presence.starting="Inicializando"
presence.rebuilding="Limpando ({0}/{1})"
presence.ready="Preparado para iniciar"